### ISSUE TITLE
Issues could provide another way for people unfamiliar with GitHub to contribute

### ISSUE THREAD

**Issue by maxspencer** [2020PB/police-brutality#35]
I think the user experience of submitting a new issue is likely better for people with no prior Git/VC knowledge. The link `https://github.com/2020PB/police-brutality/issues/new` can be used to direct users right to the new issue form. There's very little Git lingo ("fork", "commit", "branch", "pull request", etc) involved in opening an issue.

GitHub provides a way to specify "issue templates" ([docs here](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository)) which would help to ensure issues contain as much of the right information as possible. Hopefully many issues could be transferred into the actual incident report files very quickly by other users who are handy with GitHub.

I'll be happy to add an issue template and update the README if others like this idea 👍 / 👎 ?

**Comment by 2020PB** [comment]
We received a [great suggestion](https://www.reddit.com/r/2020PoliceBrutality/comments/gv3747/r2020policebrutality_github_repo_better/fsohb88/?context=3) for how to make it a lot easier for people to submit stuff without needing to make a github account or feel intimidated because they're "not coders".

I think we will implement this, have any additional suggestions / comments on the google form idea in this comment?

**Comment by 2020PB** [comment]
Also I agree with making issue templates aside from the other suggestion

**Comment by MissNeona** [comment]
Or can someone just write a bot that scans all the threads and dumps the videos somewhere just in friggin case? 

ALSO - is there a list of missing protesters to make sure they get home safe?
