### ISSUE TITLE
Add place to log protester brutality against people too

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [2020PB/police-brutality#357]
In order to have the most complete picture, brutality of protesters against protesters, protesters against passersby, and protesters against police must also be captured. Add logging for this information too. Here, for instance, a black woman was shot and killed by violent protesters while she was peacefully protesting and then getting into her car to head home. I watched the personal cell footage of the victim's sister, and it appears to maybe be a stray bullet the violent protesters fired randomly into the crowd. The frantic woman says again and again and again, "it was not the police! It was ya'all!" All violence on all sides must be logged.

Random news article on it:

https://www.kcrg.com/2020/06/03/family-of-woman-killed-in-davenport-protest-calls-for-end-to-violence/

**Comment by MicahRCM** [comment]
How about you start a repository called "protestor-brutality" then? This is not the place.

**Comment by 00000100-00010100** [comment]
Going to close this because it is outside the scope of this project. If you start your own project, you should be careful about calling people protesters unless you are absolutely certain they are actually protesters, like we know for certain the people in our project are in fact law enforcement. A better phrasing might be citizen brutality against protesters.
