### ISSUE TITLE
Canada data

### ISSUE THREAD

**Issue by alphakennyn** [2020PB/police-brutality#373]
Any thoughts on including data in Canada?

**Comment by ubershmekel** [comment]
https://github.com/2020PB/police-brutality/blob/master/CONTRIBUTING.md#content-standards

Current opinion has been USA only. Part of the reason is that we want to make these posts actionable for legislators and reporters. I would encourage you make a copy of this repository (eg fork) and start a Canada dataset.

**Comment by ubershmekel** [comment]
Please feel free to comment or re-open if needed.
