### ISSUE TITLE
Is it time to move this repo in the direction of structured data?

### ISSUE THREAD

**Issue by jMyles** [2020PB/police-brutality#83]
Instead of (or, for the moment, perhaps in addition to) markdown files, I think that we need CSVs or other structured data, with (inter alia) the following information:

* Super-brief summary
* Location
* Agency
* Structured list of officers involved, keyed by badge or serial numbers
* Name of chief or head of agency
* Status of internal disciplinary measures
* Status of complaint / criminal charges
* Contact info of at least one arbiter of redress

The reason I think that this is important is that I want to see us rapidly move our goal toward exerting pressure unto criminal charges for each and every documented incident.

Is it time for this?  Or is it premature?  I don't want to start opening pull requests with this sort of format unless there's consensus that it's timely.

**Comment by zac-towbes** [comment]
That would probably be very helpful -- I'd be happy to help out with this transition and doing it in a way which is accessible to the less technical contributors.

**Comment by Maikuolan** [comment]
If this were to happen (moving everything over to structured data), it shouldn't (in theory) be too difficult for a maintainer to write a few simple lines of code somewhere for the purpose of compiling/formatting that structured data into something else (whether that be markdown or whatever else) for the benefit of any non-technical users/readers out there interested in such a thing. So, it doesn't necessarily need to be seen as an "instead of" situation. I would suggest, convert over to structured data, but also to have an automated means of leveraging that structured data to provide back the original markdown or whatever else (e.g., to maximise the reach of the data in question, etc).

**Comment by zac-towbes** [comment]
@Maikuolan that's a good point, but I think that structured data (at least in the sense we'd be structuring data) is inaccessible to an average person, as it can easily be demonstrated using a spreadsheet, for instance. Either way, I'd be happy to write a snippet of python which turns reports into markdown from csv.

**Comment by banyanleaf** [comment]
I agree with the sentiment but I think if it can stay as accessible as possible it will be more useful. I think the folder structure works well regarding states. I would suggest to take one step further and have city sub-directories. At a city level it should help eliminate issues with the markdown files becoming large over time. I think adding a date to the markdown structure per incident would be useful. As it stands dates are inconsistent.

I submitted a PR earlier that is a dumb python3 script to parse counts and summaries out of the existing structure. At the time of creating the PR there was 117 incidents listed - I am here to help.

**Comment by Maikuolan** [comment]
Sounds good. :-)

**Comment by mnlmaier** [comment]
Maybe something which I just suggested in an issue (#133) – from a data consumption perspective, it would be great to either have CSVs or JSON files for further consumption on the frontend

**Comment by maxspencer** [comment]
> I would suggest to take one step further and have city sub-directories. At a city level it should help eliminate issues with the markdown files becoming large over time.

@banyanleaf I would suggest going one step further and simply having one file per incident and then organising those using folders. This should avoid a lot of unnecessary merge conflicts and other large-file problems and having "a file on each incident" seems quite intutive.

@jMyles if we had one file per incident then we could use YAML front matter to introduce the kind of structure you suggest in a machine and human-readable format (which is also displayed nicely by GitHub).

**Comment by 949mac** [comment]
There is a PR with a Python utility at 
https://github.com/2020PB/police-brutality/pull/110

It would be awesome if there was a /data folder with a daily data-sets, such as 2020-06-03.json, all.json, or something similar.

**Comment by ubershmekel** [comment]
I'm actively working on a continuously updating data structure. Please try to fit whatever data you want into the current markdown set up within reason. I'll update soon when it works.

**Comment by rote-culpability** [comment]
I think this is a great idea as long as all fields are optional. Tracking the victims, officers involved, their supervisors, and the repercussions is really important.

One additional suggestion is to include a field for the status of associated FOIA (freedom of information) requests for things like bodycam video of present officers. They are extremely easy to make with [MuckRock](https://www.muckrock.com/foi/create/) and people should start filing them ASAP. It may even be worth hosting a template in the repo.

**Comment by ubershmekel** [comment]
Sorry, I forgot to update this thread. The data is live at https://github.com/2020PB/police-brutality/tree/data_build

The JSON file is probably the best one to build an API and front end around.

We definitely should add more fields to the markdown and parse those out later. The reason for using markdown is that it allows more people to contribute.

I think I'd like to close this issue in favor of more specific issue per field of data you'd like to introduce. I want to make sure issues are actionable and closable. Let me know if you feel otherwise.

**Comment by tonyhb** [comment]
+1

**Comment by mnlmaier** [comment]
@tonyhb if you happen to be familiar with Nuxt/VueJS, you could check out my repo, I already started something like that :) https://github.com/mnlmaier/846-frontend
